name: Deploy Template

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-2
  AWS_ROLE: arn:aws:iam::641334985368:role/MaierBoxCFUpdateRole

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy stack to AWS
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

    - name: Deploy MaierBox Template
      id: deploy-template
      uses: aws-actions/aws-cloudformation-github-deploy@master
      with:
        name: maierbox
        template: maierbox.yml
        change-set-name: "MaierBox-cf-${{ github.sha }}"

